/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get browser map configuration */
        get: operations["getRuntimeConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find selectable chain brands */
        get: operations["listChains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode an address or place name */
        get: operations["geocode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find a shared facility or a walkable collection of stores */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a walking route through selected stores */
        post: operations["route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Longitude followed by latitude, `[longitude, latitude]`. */
        Position: [
            number,
            number
        ];
        RuntimeConfig: {
            googleMapsBrowserApiKey: string;
            googleMapsMapId: string;
        };
        SourceAttribution: {
            provider: string;
            /** Format: uri */
            providerUri?: string;
        };
        ChainInput: {
            id: string;
            name: string;
            wikidata?: string;
            aliases?: string[];
        };
        ChainOption: {
            id: string;
            name: string;
            wikidata?: string;
            aliases?: string[];
            category?: string;
        };
        /** @description A store returned by the Google-backed search service. */
        Store: {
            id: string;
            chainId: string;
            chainName: string;
            name: string;
            coordinate: components["schemas"]["Position"];
            address?: string;
            /** Format: uri */
            mapUri?: string;
            sourceAttributions?: components["schemas"]["SourceAttribution"][];
        };
        /** @enum {string} */
        SearchMode: "facility" | "walking";
        SearchRequest: {
            center: components["schemas"]["Position"];
            radiusMeters: number;
            chains: components["schemas"]["ChainInput"][];
            mode: components["schemas"]["SearchMode"];
            maxWalkMinutes?: number;
        };
        FacilityResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "facility";
            id: string;
            name: string;
            subtitle?: string;
            coordinate: components["schemas"]["Position"];
            stores: components["schemas"]["Store"][];
            sourceAttributions?: components["schemas"]["SourceAttribution"][];
        };
        WalkingResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "walking";
            id: string;
            name: string;
            coordinate: components["schemas"]["Position"];
            durationSeconds: number;
            estimatedDistanceMeters: number;
            stores: components["schemas"]["Store"][];
        };
        SearchResult: components["schemas"]["FacilityResult"] | components["schemas"]["WalkingResult"];
        SearchResponse: {
            mode: components["schemas"]["SearchMode"];
            results: components["schemas"]["SearchResult"][];
            missingChains: string[];
            /** Format: date-time */
            analyzedAt: string;
            notices: string[];
        };
        GeocodeResult: {
            id: string;
            label: string;
            coordinate: components["schemas"]["Position"];
            locality?: string;
            sourceAttributions?: components["schemas"]["SourceAttribution"][];
        };
        RouteStop: {
            id: string;
            name: string;
            coordinate: components["schemas"]["Position"];
        };
        RouteRequest: {
            stops: components["schemas"]["RouteStop"][];
        };
        GeoJsonLineString: {
            /** @constant */
            type: "LineString";
            coordinates: components["schemas"]["Position"][];
        };
        GeoJsonFeature: {
            /** @constant */
            type: "Feature";
            geometry: components["schemas"]["GeoJsonLineString"];
            properties: {
                [key: string]: unknown;
            };
        };
        GeoJsonFeatureCollection: {
            /** @constant */
            type: "FeatureCollection";
            features: components["schemas"]["GeoJsonFeature"][];
        };
        RouteResponse: {
            route: components["schemas"]["GeoJsonFeatureCollection"];
            distanceMeters: number;
            durationSeconds: number;
        };
        ApiProblem: {
            error: {
                code: string;
                message: string;
                retryable: boolean;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description A machine-readable error response. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiProblem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRuntimeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Google Maps browser configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listChains: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching chain brands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainOption"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    geocode: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked address candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResult"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    route: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description A GeoJSON LineString route. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
