export const MIN_WALK_MINUTES = 5;
export const MAX_WALK_MINUTES = 15;
export const WALK_MINUTES_STEP = 5;
const MIN_SEARCH_RADIUS_KM = 1;
const MAX_SEARCH_RADIUS_KM = 40;
export const MIN_SEARCH_RADIUS_METERS = MIN_SEARCH_RADIUS_KM * 1_000;
export const MAX_SEARCH_RADIUS_METERS = MAX_SEARCH_RADIUS_KM * 1_000;
export const SEARCH_RADIUS_STEP_METERS = 1_000;
